### ISSUE TITLE
Manual and README plugin links are broken

### ISSUE THREAD

**Issue by phgn0** [esdoc2/esdoc2#10]
### Subject of the issue
Apparently the individual plugin folders in [esdoc2-plugins](https://github.com/esdoc2/esdoc2-plugins) are in a 'packages' folder, instead of root like in [esdoc-plugins](https://github.com/esdoc/esdoc-plugins).

This breaks all github links to plugins in the manual and READMEs (as they are not updated to reflect the change). The link to 'esdoc2-standard-plugin' [here](https://github.com/esdoc2/esdoc2/blob/master/manual/migration.md#using-esdoc2-standard-plugin) is an example.

**Comment by phgn0** [comment]
I've fixed the links for esdoc2 in #11, and for esdoc2-plugins in esdoc2/esdoc2-plugins#6

**Comment by MattMcFarland** [comment]
Thanks!!!!
