### ISSUE TITLE
Can't install esdoc2

### ISSUE THREAD

**Issue by rgsilva** [esdoc2/esdoc2#2]
### Subject of the issue
I can't install esdoc2: npm will say that there isn't a compatible version for `esdoc2`, or will just fail with `esdoc2/esdoc2`. I couldn't find the reason why it won't install. I was planning on using esdoc first, but since it fails because of the huge AST at the `JSON.stringify` call, and I saw that this fork seemed to fix such issue, I decided to try this one instead.

### Your environment
* OS: Ubuntu 17.10
* Node: 6.12.0
* ESDoc2: current

### Steps to reproduce
Just try `npm install esdoc2` or `npm install esdoc2/esdoc2`.

### Expected behaviour
Expected is it to be installed :)

### Actual behaviour

First attempt:
```
ricardo@desenv4 ~/tmp $ npm install esdoc2
npm ERR! Linux 4.13.0-17-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "esdoc2"
npm ERR! node v6.12.0
npm ERR! npm  v3.10.10
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: esdoc2
npm ERR! notarget No valid targets found.
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ricardo/tmp/npm-debug.log
ricardo@desenv4 ~/tmp $ 
```

Second attempt (this fails with.. `chmod`?):
```
ricardo@desenv4 ~/tmp $ npm install esdoc2/esdoc2
npm WARN enoent ENOENT: no such file or directory, open '/home/ricardo/tmp/package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.
npm ERR! Linux 4.13.0-17-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "esdoc2/esdoc2"
npm ERR! node v6.12.0
npm ERR! npm  v3.10.10
npm ERR! path /home/ricardo/tmp/node_modules/esdoc2/out/src/ESDocCLI.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/home/ricardo/tmp/node_modules/esdoc2/out/src/ESDocCLI.js'
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/ricardo/tmp/node_modules/esdoc2/out/src/ESDocCLI.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ricardo/tmp/npm-debug.log

```

Weirdly enough, I can't see `esdoc2` with `npm view`, even though it shows in the registry (https://www.npmjs.com/package/esdoc2):

```
ricardo@desenv4 ~/tmp $ npm view --verbose esdoc2
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node', '/usr/bin/npm', 'view', '--verbose', 'esdoc2' ]
npm info using npm@3.10.10
npm info using node@v6.12.0
npm verb request uri https://registry.npmjs.org/esdoc2
npm verb request no auth needed
npm info attempt registry request try #1 at 5:22:48 PM
npm verb request id e23ad12ffe8c4d89
npm http request GET https://registry.npmjs.org/esdoc2
npm http 200 https://registry.npmjs.org/esdoc2
npm verb headers { 'content-type': 'application/json; charset=UTF-8',
npm verb headers   server: 'UploadServer',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   'last-modified': 'Wed, 22 Nov 2017 18:47:06 GMT',
npm verb headers   etag: '"5a15c62a-1eb"',
npm verb headers   'content-length': '491',
npm verb headers   'accept-ranges': 'bytes',
npm verb headers   date: 'Thu, 07 Dec 2017 19:22:48 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   age: '316',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-gru17131-GRU',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '1',
npm verb headers   'x-timer': 'S1512674569.695902,VS0,VE0',
npm verb headers   vary: 'Accept-Encoding, Accept' }
npm verb get saving esdoc2 to /home/ricardo/.npm/registry.npmjs.org/esdoc2/.cache.json
npm verb correctMkdir /home/ricardo/.npm correctMkdir not in flight; initializing
npm verb makeDirectory /home/ricardo/.npm creation not in flight; initializing
npm verb exit [ 0, true ]
npm info ok 
ricardo@desenv4 ~/tmp $ 

ricardo@desenv4 ~/tmp $ npm view esdoc2
ricardo@desenv4 ~/tmp $ 

```

**Comment by MattMcFarland** [comment]
Hi!

Thanks for reporting your issue and supplying all of the outputs.  The reason why it is failing to install is because esdoc2 requires node version 8 and yarn version 1.  https://github.com/esdoc2/esdoc2/blob/master/package.json#L15

Can you try after installing node 8?  If you dont want to use yarn, we could probably remove that as a restriction on install, but esdoc2 does use yarn workspaces to keep all of its plugins in one place.  

I also would like to suggest that you pull down and clone this repo, then remove the restrictions and use something like `npm link` to link to the repo and try installing without the engine restriction, and if it works, you can send a PR 👍 

Hope this helps!

**Comment by rgsilva** [comment]
Oh, I missed that one. Ops! That was easier than I thought. :)

With Node 8 it'll probably install just fine, but since we aren't planning on updating it soon, I decided to try with 6. I actually cloned the repo and built it with yarn and it seems to work just fine. However, I ran into a lot of other issues because of undefined stuff inside the plugins, but I'll open separate issues for that later since they are mostly plugin issues.

Thanks for the help! I might do a PR later in case you don't change the version, but I have a lot of other hacks I have to double-check first!

Cheers!

**Comment by rgsilva** [comment]
Ah, I figured out one reason why Node 8 is required: some tests are using `async`.

```
ricardo@desenv4 ~/Development/esdoc2 $ grep -r "async" --include="*.js" test 
test/integration-test/src/Async/Async.js:  async methodAsync(){}
test/integration-test/src/Async/Async.js:export async function testAsyncFunction(){}
test/integration-test/src/Async/Async.test.js:  it('is async method', ()=>{
test/integration-test/src/Async/Async.test.js:    assert.equal(doc.async, true);
test/integration-test/src/Async/Async.test.js:  it('is async function', ()=>{
test/integration-test/src/Async/Async.test.js:    assert.equal(doc.async, true);
test/integration-test/plugin/MyPlugin1.test.js:  it('calls handlers', async ()=>{
test/integration-test/plugin/MyPlugin2.test.js:  it('calls handlers', async ()=>{
```

The code, however, runs just fine, as it seems to not use `async`. Internal tests (as in esdoc2 tests) will fail, of course, but the application should run just fine. I now have mixed feelings about downgrading the required version to 6. I did that in a fork (https://github.com/rgsilva/esdoc2/commit/8027c21c2431543c701e5b9a3ea4c42649afd3ae) though, together with some extra debugging info (https://github.com/rgsilva/esdoc2/commit/720ceaa06da32e26999bc48a7614b57dedc5018b and https://github.com/rgsilva/esdoc2/commit/ee449c7449c391e910cdef73d1f01fe94e153d8e).

Any opinions regarding this?

**Comment by MattMcFarland** [comment]
Ah good catch!  I think that it would be better to get away from unsupported versions of node, but it might be ok to make this compatible with node 6 if the purpose is **not** supporting node 6 in itself.    We could swap the async usage out with Promises and it would work fine (which you might have already done perhaps) or we could remove the restriction and just warn folks that bugs wont be fixed for older unsupported versions.. Thoughts?

**Comment by rgsilva** [comment]
Dunno. Node 6 is Active LTS until next year, then it'll go into Maintenance LTS. By that time I hope we managed to upgrade our projects to 8, otherwise.. oh well :(

Node 6 won't give us any benefits whatsoever, it's more a nitpicking thing than anything, since esdoc runs on it. I didn't change the tests from `async` to `Promise`, but that's a good idea, I might do that. In my opinion, as long as all tests run, I don't see why not downgrading.

Still, _personally_, I prefer it to run at Node 8 through `nvm` and have a separate mini-project for documentation only (since our main project will stay at version 6 for a while). Whoever needs to run it at Node 6 can always clone the repository, build and manually run it themselves, like I've done here (and it works just fine).

My vote is then to stick to 8 (even for `npm` purposes), even though the code runs fine on 6. This can be, however, documented as _possible_, **but** unsupported.

**Comment by MattMcFarland** [comment]
Ahh I wasn't aware that node 6 was in LTS, I thought 8 was in LTS and 9 was latest...

**Comment by rgsilva** [comment]
It is, but it should go into Maintenance LTS in 4 months from now. Node 8 seems to be the "most active", so to speak, nowadays.

I don't mind if we stick with Node 8, but if you feel like it's worth it, we could do some quick effort to downgrade it properly to Node 6 (with all tests running, I mean). The downside is, well, it would have to be supported (which shouldn't be a big issue - I'm using it right now with a quite big project and, besides taking 15min to run, it works perfectly).

**Comment by MattMcFarland** [comment]
Well, since it is in LTS, I think we should go for supporting Node 6 👍  - I think if we swap the asyncs with Promises we should be good to go.

**Comment by rgsilva** [comment]
Now that we have official Node 6 LTS support (https://github.com/esdoc2/esdoc2/pull/3), I still can't propery install it. Not even in Node 8. This might be a local issue though, but I wanted to check with you in case you have any idea why:


```
ricardo@desenv4 ~/tmp4 $ nvm current
v8.9.2
ricardo@desenv4 ~/tmp4 $ node --version
v8.9.2
ricardo@desenv4 ~/tmp4 $ npm --version
5.5.1
```

Log file: https://pastebin.com/Nua42jdR

Using the registry:

```
ricardo@desenv4 ~/tmp4 $ npm install esdoc2
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for esdoc2

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ricardo/.npm/_logs/2017-12-11T16_49_28_706Z-debug.log
```

Using git:

```
ricardo@desenv4 ~/tmp4 $ npm install esdoc2/esdoc2
npm WARN enoent ENOENT: no such file or directory, open '/home/ricardo/tmp4/package.json'
npm WARN tmp4 No description
npm WARN tmp4 No repository field.
npm WARN tmp4 No README data
npm WARN tmp4 No license field.

npm ERR! path /home/ricardo/tmp4/node_modules/esdoc2/out/src/ESDocCLI.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/ricardo/tmp4/node_modules/esdoc2/out/src/ESDocCLI.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ricardo/.npm/_logs/2017-12-11T16_49_40_033Z-debug.log
```

Log file: https://pastebin.com/MpF4kBs8

Fun fact, with yarn I can install it, as long as I specify it as `esdoc2/esdoc2` (`esdoc2` will show no versions available and will refused to install):

```
ricardo@desenv4 ~/tmp9000 $ yarn add esdoc2/esdoc2
yarn add v1.3.2
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 143 new dependencies.
(...)
Done in 17.13s.
ricardo@desenv4 ~/tmp9000 $ 
```

**Comment by MattMcFarland** [comment]
Oh no, I see what happened.  The tag commit didn't publish to npm (I thought I set it up but apparently I didnt) - I'll publish the latest version tomorrow.

**Comment by MattMcFarland** [comment]
Done! published just now  :)

**Comment by rgsilva** [comment]
Awesome, thanks! I've managed to install, but still couldn't run it:

```
# I may have lost count of my tmp folders :-)
ricardo@desenv4 ~/tmp9999 $ node_modules/.bin/esdoc2 ~/tmp2/test/esdoc2.json 
module.js:538
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ricardo/tmp9999/node_modules/esdoc2/out/src/Factory/DocFactory.js:9:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

It seems that `npmlog` is a dev dependency instead of a runtime one. Same applies for `mkdirp`. I'll fix that in the next hours.

Now I wonder if `esdoc2-standard-plugin` and `esdoc2-publish-html-plugin` shouldn't be runtime dependencies as well. Thinking about it, it makes sense for them not to be, since one could have a different setup (different from "the standard one"). I guess we can live with that. Thoughts?

**Comment by MattMcFarland** [comment]
Thanks @rgsilva for you hard work, I've added you as contributor (sent you an invite) - as far as the plugins are concerned: I dont think they should be, but if they are always needed, it might be necessary.  Have to look into it

**Comment by rgsilva** [comment]
No problem, and thanks! I'm glad to help - I'm using the project at work anyway, and I'll most likely use it for my personal projects when I find the time to port them to ES6+. So I might as well contribute back somehow :-)

Regarding the plugins: I agree with you. I mean, they aren't really _always_ necessary, but it's more or less standard procedure to use them, unless you want to write your own. I think we can live with the current setup right now and avoid forcing unnecessary packages.

I'm glad to see that this original issue is pretty much closed by now. Even though I managed to convince people to migrate to Node 8 at work, everything should work just fine now at Node 6. I believe once we fix https://github.com/esdoc2/esdoc2/issues/6, it should be (even more) production-ready! :tada::tada:
