### ISSUE TITLE
Readme references esdoc not esdoc2

### ISSUE THREAD

**Issue by 22a** [esdoc2/esdoc2#7]
Line 33 of the readme is:
```
./node_modules/.bin/esdoc
```

should this be `esdoc2`?

```
./node_modules/.bin/esdoc2
```

**Comment by MattMcFarland** [comment]
Yes! Thanks for catching that.

**Comment by MattMcFarland** [comment]
Feel free to send PR if you have time, if not I can get to it maybe later tonight.

**Comment by rgsilva** [comment]
I took the liberty of making a PR for that, since it's an easy fix :-)
